# SPDX-FileCopyrightText: Copyright (c) 2023 - 2025 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Diffusion model sampling interface."""

from typing import Any, Dict, List

from jaxtyping import Float
from torch import Tensor

from physicsnemo.diffusion.base import DiffusionDenoiser
from physicsnemo.diffusion.noise_schedulers import NoiseScheduler

from .solvers import (
    EDMStochasticEulerSolver,
    EDMStochasticHeunSolver,
    EulerSolver,
    HeunSolver,
    Solver,
)

SOLVERS: Dict[str, type[Solver]] = {
    "euler": EulerSolver,
    "heun": HeunSolver,
    "edm_stochastic_euler": EDMStochasticEulerSolver,
    "edm_stochastic_heun": EDMStochasticHeunSolver,
}


# TODO-CURSOR: I changed my mind about the xN argument, we will keep it as it
# is now. Just double check the entire sample function below, including this
# documentation and make sure that:
# - its docstring has maximal alignment with the noise_schedulers.py in terms
#   of explanation and examples. In particular, we will revise the examples and
#   have 3 examples in the docstring.
#   The first example should be as simple as possible, and the two other
#   examples should have incremental complexity, but still remain as crisp as
#   possible. The second example should show a little more customization in the
#  argument passed to the sample function. The last examples should show that
#  it's not necessary to actually import anything from noise_schedulers.py. It
#  should just define a scheduler from scratch using the base NoiseScheduler
#  protocol (kinda bare bone maximal flexibility approach).
# - You will double check the signatures of all methods from the
#   noise_schedulers to make sure that they are consistent with the base NoiseScheduler
#   protocol.


def sample(
    denoiser: DiffusionDenoiser,
    xN: Float[Tensor, "B *dims"],  # noqa: F821
    noise_scheduler: NoiseScheduler,
    num_steps: int,
    solver: str | Solver = "heun",
    time_steps: Float[Tensor, "N"] | None = None,  # noqa: F821
    solver_options: Dict[str, Any] | None = None,
    time_eval: list[int] | None = None,
) -> Float[Tensor, "B *dims"] | List[Float[Tensor, "B *dims"]]:  # noqa: F821
    r"""
    Generate batched samples from a diffusion model.

    This interface is quite generic and can be used to generate samples from
    any reverse diffusion process of the form:

    .. math::
        \mathbf{x}_{n-1} = G (\mathbf{x}_{i \geq n}, t_{i \geq n-1})

    This covers both ODE/SDE-based sampling (e.g. VP, VE, EDM) and discrete
    Markov chain-based sampling (e.g. DDPM). The exact expression of the
    operator :math:`G` depends on the combination of:

    - The ``solver``, which determines the numerical method to update
      the latent state :math:`\mathbf{x}_n` at each time-step.
    - The ``denoiser``, which can be the right hand side for ODE/SDE-based
      sampling, the denoised latent state for discrete Markov chain-based
      sampling, etc.

    Typically, the update applied is roughly:

    .. math::
        \mathbf{x}_{n-1} = \text{Step}(F(\mathbf{x}_n, t_n);
        \mathbf{x}_n, t_n, t_{n-1})

    where :math:`F` is the ``denoiser`` and :math:`\text{Step}` is the
    update rule of the solver, implemented by the
    :meth:`~physicsnemo.diffusion.samplers.solvers.Solver.step` method.
    Variants are possible by passing more complex solvers and denoisers.

    The ``solver`` can be specified as a string key (with optional
    ``solver_options``), or as a pre-configured object implementing the
    :class:`~physicsnemo.diffusion.samplers.solvers.Solver` interface (in
    which case ``solver_options`` must be ``None``). The solver must implement
    a ``step`` method with the following signature:

    .. code-block:: python

        def step(self, x: Tensor, t_cur: Tensor, t_next: Tensor) -> Tensor: ...

    Any object that implements the
    :class:`~physicsnemo.diffusion.samplers.solvers.Solver` interface can be
    used as a solver.

    The ``denoiser`` must implement the
    :class:`~physicsnemo.diffusion.DiffusionDenoiser` interface, with the
    following signature:

    .. code-block:: python

        def denoiser(x: Tensor, t: Tensor) -> Tensor: ...

    Any object that implements the
    :class:`~physicsnemo.diffusion.DiffusionDenoiser` interface can be used as
    a denoiser.

    Time-steps are generated by the ``noise_scheduler`` using its
    :meth:`~physicsnemo.diffusion.noise_schedulers.NoiseScheduler.timesteps`
    method with the provided ``num_steps``. To use custom time-steps, pass a
    1D tensor to ``time_steps`` which will override the schedule's time-steps.

    Parameters
    ----------
    denoiser : DiffusionDenoiser
        A callable that takes ``(x, t)`` and returns a denoising term with the
        same shape as the latent state ``xN``. See
        :class:`~physicsnemo.diffusion.DiffusionDenoiser` for the expected
        interface. Can usually be obtained by using
        :meth:`~physicsnemo.diffusion.noise_schedulers.NoiseScheduler.get_denoiser`
        from a noise scheduler (typically from the same noise scheduler
        instance as the ``noise_scheduler`` argument, but can be different if
        desired).
    xN : Tensor
        Initial noisy latent state :math:`\mathbf{x}_N` of shape :math:`(B, *)`
        where :math:`B` is the batch size. All batch elements share the same
        diffusion time values. The ``dtype`` and ``device`` of ``xN`` determine
        the ``dtype`` and ``device`` of the generated samples and any
        internally created tensors. Can usually be obtained by using
        :meth:`~physicsnemo.diffusion.noise_schedulers.NoiseScheduler.init_latents`
        from a noise scheduler (typically from the same noise scheduler
        instance as the ``noise_scheduler`` argument, but can be different if
        desired).
    noise_scheduler : NoiseScheduler
        The noise scheduler instance used for generating time-steps. The
        schedule's
        :meth:`~physicsnemo.diffusion.noise_schedulers.NoiseScheduler.timesteps`
        method is called with ``num_steps`` to produce the diffusion time
        values, unless ``time_steps`` is provided to override them.
    num_steps : int
        Number of sampling steps. Passed to the noise scheduler's
        :meth:`~physicsnemo.diffusion.noise_schedulers.NoiseScheduler.timesteps`
        method. Ignored when ``time_steps`` is provided.
    solver : str | Solver, default="heun"
        The numerical solver to use. Can be a string key or an object
        implementing the
        :class:`~physicsnemo.diffusion.samplers.solvers.Solver` interface.
        When ``solver`` is a string, ``solver_options`` can be provided to
        configure the solver; when it is a
        :class:`~physicsnemo.diffusion.samplers.solvers.Solver` instance,
        ``solver_options`` must be ``None``. Available string keys are:

        * ``"euler"``: First-order Euler method. Fast but lower quality.
          See :class:`~physicsnemo.diffusion.samplers.solvers.EulerSolver`.

        * ``"heun"``: Second-order Heun method. Higher quality but requires
          two denoiser evaluations per step.
          See :class:`~physicsnemo.diffusion.samplers.solvers.HeunSolver`.

        * ``"edm_stochastic_euler"``: First-order stochastic sampler from
          the EDM paper with configurable noise injection. See
          :class:`~physicsnemo.diffusion.samplers.solvers.EDMStochasticEulerSolver`.

        * ``"edm_stochastic_heun"``: Second-order stochastic sampler from
          the EDM paper with configurable noise injection. See
          :class:`~physicsnemo.diffusion.samplers.solvers.EDMStochasticHeunSolver`.

    time_steps : Tensor | None, default=None
        Optional 1D tensor of shape :math:`(N + 1,)` containing explicit
        diffusion time values :math:`t_N, t_{N-1}, ..., t_0` in decreasing
        order. If provided, overrides the time-steps from ``noise_scheduler``
        and ``num_steps`` is ignored. To produce a fully denoised latent state
        :math:`\mathbf{x}_0`, the last element must be :math:`t_0 = 0`.
    solver_options : Dict[str, Any] | None, default=None
        Additional options passed to the solver constructor. Only used when
        ``solver`` is a string; must be ``None`` when ``solver`` is a
        :class:`Solver` instance. See individual solver classes for available
        options.
    time_eval : List[int] | None, default=None
        Indices of time-steps at which to return intermediate samples. If
        provided, returns a list of tensors. If ``None``, returns only the
        final denoised latent state :math:`\mathbf{x}_0`.

    Returns
    -------
    Tensor | List[Tensor]
        If ``time_eval`` is ``None``, returns the final denoised latent state
        :math:`\mathbf{x}_0` of shape :math:`(B, *)`. Otherwise, returns a list
        of tensors :math:`\mathbf{x}_t` of shape :math:`(B, *)` containing
        latent states at time-step indices specified in ``time_eval``.

    See Also
    --------
    :mod:`~physicsnemo.diffusion.samplers.solvers` : Available ODE/SDE solvers.
    :mod:`~physicsnemo.diffusion.noise_schedulers` : Available noise schedules.

    Examples
    --------

    # TODO-CURSOR: these exxamples are okay-ish, but that's mot really what I
    was thinking of.
    - In examples 1 and 2 the denoiser should be coming from the
    noise scheduler itself, not from the user. That's the normal usage pattern.
    In the example 3 it can be created by the user from scratch.
    **Example 1:** Minimal usage with built-in noise scheduler.
    - Same thing for the xN which should be coming from the noise scheduler
    itself, with the init_latents method.

    >>> import torch
    >>> from physicsnemo.diffusion.samplers import sample
    >>> from physicsnemo.diffusion.noise_schedulers import EDMNoiseScheduler
    >>>
    >>> denoiser = lambda x, t: x * 0.9
    >>> scheduler = EDMNoiseScheduler()
    >>> xN = torch.randn(2, 3, 8, 8) * 80
    >>> x0 = sample(denoiser, xN, scheduler, num_steps=10)
    >>> x0.shape
    torch.Size([2, 3, 8, 8])

    **Example 2:** Using custom time-steps and the Euler solver for faster
    sampling.

    >>> import torch
    >>> from physicsnemo.diffusion.samplers import sample
    >>> from physicsnemo.diffusion.noise_schedulers import EDMNoiseScheduler
    >>>
    >>> denoiser = lambda x, t: x * 0.9
    >>> scheduler = EDMNoiseScheduler()
    >>> xN = torch.randn(2, 3, 8, 8) * 80
    >>> custom_t = torch.tensor([80.0, 40.0, 20.0, 10.0, 5.0, 0.0])
    >>> x0 = sample(denoiser, xN, scheduler, num_steps=0, time_steps=custom_t,
    ...             solver="euler")
    >>> x0.shape
    torch.Size([2, 3, 8, 8])

    **Example 3:** Bare-bone approach defining a custom scheduler from scratch
    without importing any noise scheduler class. Any object implementing the
    :class:`~physicsnemo.diffusion.noise_schedulers.NoiseScheduler` protocol
    can be used:

    >>> import torch
    >>> from physicsnemo.diffusion.samplers import sample
    >>>
    >>> class MinimalScheduler:
    ...     def timesteps(self, num_steps, *, device=None, dtype=None):
    ...         return torch.linspace(1.0, 0.0, num_steps + 1,
    ...                               device=device, dtype=dtype)
    ...     def sample_time(self, N, *, device=None, dtype=None):
    ...         return torch.rand(N, device=device, dtype=dtype)
    ...     def add_noise(self, x0, time):
    ...         return x0 + time.view(-1, 1, 1, 1) * torch.randn_like(x0)
    ...     def init_latents(self, spatial_shape, tN, *, device=None,
    ...                      dtype=None):
    ...         return torch.randn(tN.shape[0], *spatial_shape,
    ...                            device=device, dtype=dtype)
    ...     def get_denoiser(self, denoiser_in, **kwargs):
    ...         return denoiser_in
    >>>
    >>> denoiser = lambda x, t: x * 0.9
    >>> scheduler = MinimalScheduler()
    >>> xN = torch.randn(2, 3, 8, 8)
    >>> x0 = sample(denoiser, xN, scheduler, num_steps=10, solver="euler")
    >>> x0.shape
    torch.Size([2, 3, 8, 8])
    """
    solver_options = solver_options or {}

    # Validate and instantiate solver
    if isinstance(solver, str):
        if solver not in SOLVERS:
            available = ", ".join(f'"{k}"' for k in SOLVERS.keys())
            raise ValueError(
                f"Unknown solver '{solver}'. Available solvers: {available}."
            )
        solver_cls = SOLVERS[solver]
        solver_ = solver_cls(denoiser, **solver_options)
    else:
        # Assume solver is a Solver-like object with a step method
        if solver_options:
            raise ValueError(
                "solver_options must be None when solver is a Solver instance."
            )
        solver_ = solver

    # Generate time-steps from noise_scheduler or use provided ones
    if time_steps is not None:
        t_steps = time_steps.to(device=xN.device, dtype=xN.dtype)
    else:
        t_steps = noise_scheduler.timesteps(num_steps, device=xN.device, dtype=xN.dtype)

    # Main sampling loop
    samples: List[Tensor] = []
    x = xN
    n_steps = len(t_steps) - 1  # Last element is 0 (final time)

    for i in range(n_steps):
        t_cur = t_steps[i]
        t_next = t_steps[i + 1]

        # Expand t to batch dimension: scalar -> (B,)
        batch_size = x.shape[0]
        t_cur_batch = t_cur.expand(batch_size)
        t_next_batch = t_next.expand(batch_size)

        # Perform one solver step
        x = solver_.step(x, t_cur_batch, t_next_batch)

        # Collect sample if requested
        if time_eval is not None and i in time_eval:
            samples.append(x.clone())

    # Return based on time_eval
    if time_eval is not None:
        return samples

    return x
