# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

hydra:
  job:
    chdir: true
    name: regression  # choose from [regression, diffusion, patched_diffusion]
  run:
    dir: ./outputs/${hydra:job.name}

# Get defaults
defaults:

  # Dataset
  - dataset/cwb_train

  # Model
  - model/corrdiff_regression

  # Training
  - training/corrdiff_regression

  # Validation (comment out to disable validation)
  - validation/cwb

# Parameters for wandb logging
wanbd:
  key: <your_api_key>
  # You wandb API key
  project: <your_project_name>
  # Your wanb project name
  entity: <your_entity_name>
  # Name of your wandb enity
  name: <your_experiment_name>
  # Name of your experiment
  mode: online
  # Logging mode. Accepted values: "offline", "online" or "disabled"
  watch_model: true
  # Bool: if true, then wandb logs statistics about your model parameters