# SPDX-FileCopyrightText: Copyright (c) 2023 - 2024 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Model configuration
model:
  regression_checkpoint_path: regression_checkpoint/ElasticNet.0.85.mdlus  # Path to regression model checkpoint
  conditioning_model_type: "FNO"  # Type of conditioning model. Must be "FNO or "ResNet".
  conditioning_model_kwargs:
    pos_embd_channels: 16  # Number of channels for the positional embedding
  model_args:
    model_channels: 64  # Base multiplier for the number of channels across the network
    channel_mult: [1, 2, 2]  # Per-resolution multipliers for the number of channels
    attn_resolutions: [17]  # Resolutions at which self-attention layers are applied
    cond_concat_resolution: 70  # Resolution at which to concatenate the
    gridtype: "linear"  # Type of positional embedding grid
    N_grid_channels: 2  # Number of channels for the positional embedding grid
    
  
# Dataset configuration
dataset:
  name: "CFB"  # Dataset name
  directory: "../data/raw_dataset"  # Training data directory
  nb_sources: 5  # Number of input channels for each input (ux, uz)
  nb_timesteps: 1000  # Number of timesteps (height of the input image)
  nb_receivers: 70  # Number of receivers (width of the input image)
  subsurface_resolution: [70, 70]  # Resolution of subsurface image (shape of output image)
  transform: "ZscoreNormalize"  # Data transform: "ZscoreNormalize" or "MinMaxNormalize"

# Training configuration
training:
  batch_size_per_device: 4  # Batch size per device for training
  max_epochs: 100  # Maximum number of epochs
  lr: 1.0e-3  # Initial learning rate
  weight_decay: 1.0e-4  # Weight decay for optimizer
  num_workers: 1  # Number of workers for data loading
  scheduler:
    patience: 5  # Epochs without improvement before reducing learning rate
    factor: 0.2  # Factor by which learning rate will be reduced

# Validation configuration
val:
  batch_size_per_device: 4  # Batch size per device for validation
  num_workers: 1  # Number of workers for validation data loading

# I/O configuration
io:
  load_checkpoint: false  # Whether to load a checkpoint
  checkpoint_dir: "./checkpoints/"  # Directory to save checkpoints
  checkpoint_freq: 10  # Save checkpoint every N epochs
  log_freq: 10  # Log frequency (in batches)

# Wandb configuration
wandb:
  mode: "offline"  # "online", "offline", or "disabled"
  results_dir: "./wandb/"  # Directory to save wandb logs
  entity: "modulus"  # Entity (username or team name) for Weights & Biases
